services:
  postgres:
    image: postgres:16-alpine
    container_name: sso-postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5454:5432"          # ← внешний порт любой
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    image: migrate/migrate:4
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@postgres:5432/authdb?sslmode=disable",
      "up"
    ]
    restart: "no"

volumes:
  pgdata:
